import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { Toaster } from "react-hot-toast";

const inter = Inter({
	subsets: ["latin", "cyrillic"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} antialiased px-10 py-5 flex-1 w-screen h-screen`}
			>
				<Navigation />
				{children}
				<Toaster position="top-right" />
			</body>
		</html>
	);
}
